name: of_kit
description: of_kit is a quick develop utils collection for flutter.
version: 0.0.1
author: Panda <panda@cvbro.io>
homepage: https://ofkit.open.openflutter.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # common dependencies
  sprintf: ^4.0.0
  path: ^1.6.2

  # kv_store dependencies
  sqflite: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.openflutter.of_kit
    pluginClass: OfKitPlugin