name: of_cache
description: of_cache is a convenient storage/cache kit for flutter.
version: 0.0.1
author: Panda <panda@cvbro.io>
homepage: https://github.com/PandaCVBRO/of_kit

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sprintf: ^4.0.0
  path: ^1.6.2
  sqflite: ^1.1.0
  of_logger: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.openflutter.plugins.of_cache
    pluginClass: OfCachePlugin
